//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.296
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AdminSuite.Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Customers {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Customers() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("AdminSuite.Resources.Customers", typeof(Customers).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to mcomm_test;123456.
        /// </summary>
        internal static string BannedCountryCustomer {
            get {
                return ResourceManager.GetString("BannedCountryCustomer", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to CompEx_mcomm_03;123456.
        /// </summary>
        internal static string CompanyExcludedCustomer {
            get {
                return ResourceManager.GetString("CompanyExcludedCustomer", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to test_aditi_UK4;123456.
        /// </summary>
        internal static string DefaultBetaCustomer {
            get {
                return ResourceManager.GetString("DefaultBetaCustomer", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to mcomm_test;123456.
        /// </summary>
        internal static string HVCCustomer {
            get {
                return ResourceManager.GetString("HVCCustomer", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to testaditimanjugbp;123456.
        /// </summary>
        internal static string LiveCustomer {
            get {
                return ResourceManager.GetString("LiveCustomer", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to AccLock_mcomm_04;123456.
        /// </summary>
        internal static string LockAttemptCustomer {
            get {
                return ResourceManager.GetString("LockAttemptCustomer", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SeldEx_mcomm_02;123456.
        /// </summary>
        internal static string SelfExcludedCustomer {
            get {
                return ResourceManager.GetString("SelfExcludedCustomer", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to testaditiagbp;123456.
        /// </summary>
        internal static string StageCustomer {
            get {
                return ResourceManager.GetString("StageCustomer", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to susp_mcomm_01;123456.
        /// </summary>
        internal static string SuspendedCustomer {
            get {
                return ResourceManager.GetString("SuspendedCustomer", resourceCulture);
            }
        }
    }
}
